name: Command-Line Tool
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - uses: actions/checkout@v2
      - name: test build-Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          python-version: 3.8
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        run: |
          make install
      - name: Format
        run: |
          make format
      - name: Linting
        run: |
          make lint
      - name: Testing
        run: |
          make test
      - name: Deploy
        run: |
          make deploy
